sudo: false

language: rust
matrix:
  include:
    - os: linux
      rust: nightly-2019-12-20
    - os: osx
      rust: nightly-2019-12-20
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add clippy; fi

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo fmt -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo clippy -- -D clippy::all; fi
  - cargo test --all -- --nocapture
  - cargo test --all --all-features -- --nocapture
  # Validate features and benches too.
  - cargo bench --all -- --test
  - cargo bench --all --all-features -- --test
